env:
  contexts:
    - name: "React App Context"
      urls:
        - "http://host.docker.internal:5173"
      includePaths:
        - "http://host.docker.internal:5173.*"

parameters:
  failOnError: false
  failOnWarning: false

jobs:
  - type: "spiderAjax"
    parameters:
      context: "React App Context"

  - type: "passiveScan-config"
    rules:
      - id: 10038
        threshold: "off"
      - id: 10010
        threshold: "high"

  - type: "passiveScan-wait"
  - type: "report"
    parameters:
      template: "risk-confidence-html"
      reportDir: "/zap/wrk"
      reportFile: "zap-report"
